site_name: Airline Tycoon
site_url: https://brianelinsky.github.io/Airline_Tycoon/
site_description: Build and operate your own airline in this charming simulation game inspired by RollerCoaster Tycoon
site_author: Brian Elinsky

repo_url: https://github.com/brianelinsky/Airline_Tycoon
repo_name: Airline_Tycoon

copyright: Copyright &copy; 2025 Brian Elinsky - All rights reserved

theme:
  name: material
  favicon: logo.png
  logo: logo.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - navigation.tabs
    - content.code.copy
    - content.code.annotate
    - search.highlight
    - search.share
  palette:
    - scheme: default
      primary: white
      accent: light-blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: grey
      accent: light-blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

plugins:
  - search
  - section-index

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - footnotes
  - attr_list
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mermaid.js
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js

nav:
  - Home: index.md
  - Game Vision: vision.md
  - Getting Started:
    - Development Setup: how-to/setup-dev-environment.md
    - Start Coding: how-to/start-coding.md
  - Game Design:
    - Core Concepts: explanation/core-concepts.md
    - Game Mechanics: explanation/game-mechanics.md
    - Economic Model: explanation/economic-model.md
    - Airline Types: explanation/airline-types.md
    - Seasonal System: explanation/seasonal-system.md
  - Architecture:
    - System Overview: explanation/architecture.md
    - Components: reference/components.md
    - Design Patterns: reference/design-patterns.md
    - Event System: reference/event-system.md
  - Development:
    - Coding Standards: reference/coding-standards.md
    - Testing Guide: how-to/testing-guide.md
    - Contributing: how-to/contributing.md
    - C# Conventions: reference/csharp-conventions.md
  - Tutorials:
    - Your First Feature: tutorials/first-feature.md
    - Adding Airlines: tutorials/adding-airlines.md
    - Creating Routes: tutorials/creating-routes.md
    - Implementing Events: tutorials/implementing-events.md
  - API Reference:
    - Game Engine: reference/api/game-engine.md
    - Flight System: reference/api/flight-system.md
    - Economic System: reference/api/economic-system.md
    - AI System: reference/api/ai-system.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/brianelinsky/Airline_Tycoon
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY